- hosts: localhost
  name: init
  connection: local
  gather_facts: False
  vars:
    count: 1
  roles: 
    - build-ami
  tags:
    - init

  tasks:
    - name: Provision a set of instances
      local_action:
        module: ec2
        # this allows to refer to them later via 'hosts: key_raiden'
        key_name: raiden
        region: "{{ region }}"
        group: raiden
        instance_type: "{{ instance_type }}" 
        image: "{{ ami_id }}"
        wait: true
        count: "{{ count }}"
        instance_tags:
          Name: Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=key_raiden
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2.instances }}"

- hosts: key_raiden
  name: install geth 
  remote_user: "{{ remote_user }}"
  gather_facts: true
  roles:
    - build-ami
  tags:
    - install_geth

  tasks:
    - name: add ethereum ppa
      shell: sudo add-apt-repository ppa:ethereum/ethereum -y

    - name: install geth, solc
      apt: name="{{ item }}" update_cache=yes
      sudo: yes
      with_items:
        - geth
        - solc

- hosts: key_raiden
  name: install raiden 
  remote_user: "{{ remote_user }}"
  gather_facts: true
  roles:
    - build-ami
  tags:
    - install_raiden 

  tasks:
    - name: install raiden system dependencies 
      apt: name="{{ item }}" update_cache=yes
      sudo: yes
      with_items:
        - git-core
        - python-pip
        - python-dev
        - python-virtualenv
        - build-essential
        - automake
        - pkg-config
        - libtool
        - libffi-dev
        - libgmp-dev
        - libssl-dev

    - name: clone raiden
      git: 
        repo: "https://github.com/raiden-network/raiden"
        update: yes
        version: "{{ raiden_version }}"
        dest: "{{ raiden_dir }}"

    - name: update setuptools
      pip:
        name: setuptools
        virtualenv: "/home/ubuntu/raidenvenv"
        state: forcereinstall

    - name: install raiden
      pip:
        name: "."
        virtualenv: "/home/ubuntu/raidenvenv"
        chdir: "{{ raiden_dir }}"

- hosts: key_raiden
  name: terminate
  remote_user: "{{ remote_user }}"
  gather_facts: False
  roles:
    - build-ami
  tags:
    - terminate

  tasks:
    # Collect instance id: http://stackoverflow.com/a/27307254 
    - action: ec2_facts
    - name: shutdown all ec2.instances
      local_action:
        module: ec2
        region: "{{ region }}"
        state: absent
        instance_ids: "{{ ansible_ec2_instance_id }}"
      when: keep is not defined
