language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
notifications:
  slack:
    secure: S95dDs65iw6rea1MKY5BNb7HrPDDeLPVNiU9KrVrJ9wk5mvDjpGxoFyzrop1IG7s+Ekqx0TKi0fX27btOyzy5R1Jue73N8KhRptcvC18Z4n8rrvXi28bgmGqp/5amhiQnyFuWjIjOylwDsvgXUqrqcOnOafFnodbm+QP1qWIFkPlw9mUEPcNUNqOrW5u+erE66yK50WqBd4l9eiK5J/fYEgxXXJLZhr4f0cue7OY/iH6ZsL68thvdXhYFmZZWWEdpLGU7HYJ389mlUXEuXa2ZoSGB+eDuoHYvi8CIFPmDsIs8qHZxG/XTquTv7yCymn6bLWdQ4zRMdjY4tXB8kVUAKJtGe/x9xsfEJ9ZAJm0MhFIswThiTN+t9bRsGecG8+3IA43bLD+svoZWOIo9pCdA800FkNvqf9xdAwHVRpYDRlVFRYYuCvnXpsNr+wzi03kAE5WksgVflgwuoU/FXyBZya9bO+IlEfvVTceGb1RV1b8WsKEcGJfSj3XFR5JSSutbl/JeeHVqc6qgiJPnaDymM7BrnbhBEoGviz72aaKxeXyAcYTcYOu1vGLjxxEo1pE9rEtgQjyUZEMwXKtap76L94EY/YmCiOpWGzs2DlwZ7g0y/69qMg3frxJGuMng4WhoJy/inithu6xCpFSZpzkFQq/kzCeKAZdrpvsEJ+CzX8=
script:
- coverage run --source raiden setup.py test
after_success:
- coveralls
