# Config file for automatic testing at travis-ci.org

language: python

python:
  #- "3.4"
  - "2.7"
  #- "pypy"
  #- "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -r requirements.txt
 - pip install coveralls

notifications:
    slack: chainbot:F7iOw4oESj1hMPeoZRZsYhKC #brainbot dev-raiden slack channel

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source raiden setup.py test

after_success:
  - coveralls
